"""initial migration

Revision ID: 2a176441c45c
Revises: 
Create Date: 2025-05-23 13:57:36.666839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a176441c45c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('fuel_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('guide_number', sa.String(length=64), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('service_station', sa.String(length=100), nullable=True),
    sa.Column('supply', sa.String(length=50), nullable=True),
    sa.Column('kilometers', sa.Integer(), nullable=True),
    sa.Column('consumption', sa.Float(), nullable=True),
    sa.Column('image_filename', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_record_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_record_date'))

    op.drop_table('fuel_record')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
